### ISSUE TITLE
KISS to PDU block problem

### ISSUE THREAD

**Issue by SterlingPeet** [daniestevez/gr-kiss#2]
It seems like something is wrong with the KISS to PDU block, it seems to be unconnected in all the examples.  It looks like the flow graph is set up expecting it to have a PDU input that comes from the TCP Server block, but the input type is (packed?) bytes and does not connect.  Is there an error in the block, or uncommitted/pushed code that makes it work?

**Comment by daniestevez** [comment]
At some point the input format for the KISS to PDU input format changed from "message" to "byte", but I forgot to change the examples accordingly. I have just fixed this.
